### ISSUE TITLE
Hello there, I need some help

### ISSUE THREAD

**Issue by X1aoyueyue** [RossDynamics/LCS-Tools#1]
Hello, creators. Firstly, I appreciate it that you upload your codes to Github, which makes it possible for me to use your codes.

I am working on the search of FTLE and I want to find a appropriate program to extract the ridges. I think your program is excellent. So I downloaded the ZIP and have tried to run it. I made up the environment and ran the _Ridges_Filtered_LCS_Extractions_Test.py_successfully. But unfortunately, I did not know the format of input files, especially the input file of the above script.

Therefore, it is sticky to make your codes avaliable for my project. If you could discuss with me how you make up the data files, I would be appreciated. Thanks for your help.

**Comment by hokiepete** [comment]
Hello, sorry for the delay getting back to you. IIRC this was written to work with Philip Du Toit's FTLE calculator "NEWMAN". It takes the FTLE field generated by that. Over at my github I have a repo, "dynamics-lab-starter-kit" which should contain much more useful files for you. In particular here is one script that should walk you through computing infinitesimal-time lagrangian exponent structures.
https://github.com/hokiepete/dynamics-lab-starter-kit/blob/master/compute_iLCS.py

They're basically the same as LCS but there's no need for integration. It's based on this paper here
https://link.springer.com/article/10.1007/s11071-020-05713-4

If you want to calculate LCS instead you could replace the Eulerian rate-of-strain tensor S with the Cauchy-Green strain tensor C and the rest of the code should work more or less the same, at least everything being calculated from the max eigenvector should work, the min eigenvector code you'd want to remove since it's not applicable with C.
